### ISSUE TITLE
Stream not reconnecting

### ISSUE THREAD

**Issue by NicolasCharpentier** [LearnersGuild/rethinkdb-changefeed-reconnect#5]
Hey, me again.

My changestream is not reconnecting when I restart my rethinkdb instance.

Using it this way (version 0.3.0):

![image](https://cloud.githubusercontent.com/assets/9944995/20610315/f41ccd76-b297-11e6-8521-12eb4f60e234.png)

The error : 

![image](https://cloud.githubusercontent.com/assets/9944995/20610328/2f9b9dd2-b298-11e6-8225-d011b07097c0.png)

After error happened, I wont see any other messages from your library, and pushing new values into rethink wont call my handleItemCallback.

Thank you, ask me for anything if you need more information / tests from me

Ps / Edit : Of course, my driver connects back with the rethinkdb-node after restart

**Comment by jeffreywescott** [comment]
Interesting.

It looks like you're getting a `ReqlOpFailedError`, but we're only checking for:

- `ReqlServerError`
- `ReqlDriverError`

It's tricky -- I don't want to catch _all_ `ReqlXXXError` errors, because if there's a problem with the query, or some non-connection-related error, I want the error to propagate out to the caller. It seems like `ReqlOpFailedError` exceptions _could_ be possible outside of connection issues.

I guess I could do something ugly like look for `Changefeed aborted` in the error message itself, though that seems hacky at best.

What do you think?

Here's the relevant code: https://github.com/LearnersGuild/rethinkdb-changefeed-reconnect/blob/master/src/index.js#L82-L84

Just to make sure I'm not crazy, you could add `ReqlOpFailedError` to that function and see if it works for you? You'll need to add it in `lib` rather than `src` ...

**Comment by NicolasCharpentier** [comment]
Hey.

It is tricky yes, If i were you i'd put the whole parent class (`ReqlAvailabilityError `) of network errors, even if they may happen from another cause (configuration as I understand), because this is what you do, restart stream in network errors.

I understand the consequences of the choice, i'll let this for you, the string indexOf() could be the choice, but yep hacky..

As for my tests, I am sorry to announce you that I don't have anymore time at the moment for this project, tried fast and could not make it work (with just an instanceof test), maybe `ReqlOpFailedError` is not an error type but just a name of a `ReqlRunTimeError` ?

From `rethinkdbdash/lib/error`

![image](https://cloud.githubusercontent.com/assets/9944995/20727713/ee734e9a-b67a-11e6-84ee-f5a3a544a626.png)

Wish you luck on this.

You can reproduce this by using docker containers for emulating rethink cluster, and just dropping one.

**Comment by jeffreywescott** [comment]
Thanks, @NicolasCharpentier. I'll follow-up here once I find / have a fix, in case you want to try it out again.

**Comment by jeffreywescott** [comment]
In the end, I resorted to RegExp matches on the error string -- not ideal, but seems to work now for use on clusters / via a proxy node.
